// <auto-generated />
namespace MobileAppDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class locations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(locations));
        
        string IMigrationMetadata.Id
        {
            get { return "201509282144204_locations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
