// <auto-generated />
namespace MobileAppDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Customers1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customers1));
        
        string IMigrationMetadata.Id
        {
            get { return "201509242312412_Customers1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
